<?php
// Variables
return [
  "creatorName" => "ZANA",
  "creatorUrl" => "#",
  "templateName" => "ZANA",
  "templateSuffix" => "Gestor de Taller",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Gestor de Taller",
  "templateKeyword" => "gestor, taller, admin",
  "licenseUrl" => "#",
  "livePreview" => "#",
  "productPage" => "#",
  "support" => "#",
  "adminTemplates" => "#",
  "bootstrapDashboard" => "#",
  "ogTitle" => "Gestor de Taller",
  "ogImage" => "",
  "ogType" => "website",
  "moreThemes" => "#",
  "documentation" => "#",
  "repository" => "#",
  "gitRepo" => "#",
  "gitRepoAccess" => "#",
  "githubFreeUrl" => "#",
  "facebookUrl" => "#",
  "twitterUrl" => "#",
  "githubUrl" => "#",
  "dribbbleUrl" => "#",
  "instagramUrl" => "#"
];
